import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import { TENANT_ADMIN } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const tenantAdminNavigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
    {
        key: 'POS',
        path: '',
        title: 'POS',
        translateKey: 'nav.orders.pos',
        icon: 'orders',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [TENANT_ADMIN],
        subMenu: [
            {
                key: 'orders.panel',
                path: '/orders/panel',
                title: 'Order Panel',
                translateKey: 'nav.orders.panel',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TENANT_ADMIN],
                subMenu: [],
            },
            {
                key: 'orders.all',
                path: '/orders/all',
                title: 'All Orders',
                translateKey: 'nav.orders.all',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [TENANT_ADMIN],
                subMenu: [],
            },
        ],
    },
        {
        key: 'online_orders',
        path: '/online-orders',
        title: 'Online Orders',
        translateKey: 'nav.onlineOrders',
        icon: 'orders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
    {
        key: 'menu',
        path: '/menu',
        title: 'Menu',
        translateKey: 'nav.menu',
        icon: 'menu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
    {
        key: 'tableManagement',
        path: '/table-management',
        title: 'Table Management',
        translateKey: 'nav.tableManagement',
        icon: 'tableManagement',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
    {
        key: 'staffs',
        path: '/staffs',
        title: 'Staffs',
        translateKey: 'nav.staffs',
        icon: 'staffs',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
    {
        key: 'kitchenManagement',
        path: '/kitchen-management',
        title: 'Kitchen Management',
        translateKey: 'nav.kitchenManagement',
        icon: 'kitchenManagement',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
    {
        key: 'expenseTracker',
        path: '/expense-tracker',
        title: 'Expense Tracker',
        translateKey: 'nav.expenseTracker',
        icon: 'expenseTracker',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
    {
        key: 'customers',
        path: '/customers',
        title: 'Customers',
        translateKey: 'nav.customers',
        icon: 'customers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
    {
        key: 'report',
        path: '/report',
        title: 'Report',
        translateKey: 'nav.report',
        icon: 'report',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [TENANT_ADMIN],
        subMenu: [],
    },
]

export default tenantAdminNavigationConfig
